import React, { useEffect, useRef, useState } from 'react';
import * as joint from 'jointjs';
import 'jointjs/dist/joint.css';

interface JointJsDiagramProps {
  jsonGraph: string;
}

export function JointJsDiagram({ jsonGraph }: JointJsDiagramProps) {
  const canvasRef = useRef<HTMLDivElement>(null);
  const graphRef = useRef<joint.dia.Graph | null>(null);
  const paperRef = useRef<joint.dia.Paper | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!canvasRef.current) return;

    if (!graphRef.current) {
      graphRef.current = new joint.dia.Graph();
      paperRef.current = new joint.dia.Paper({
        el: canvasRef.current,
        model: graphRef.current,
        width: '100%',
        height: '100%',
        gridSize: 10,
        drawGrid: true,
        background: { color: '#0f172a' },
        interactive: true,
      });
    }

    const graph = graphRef.current;

    if (jsonGraph) {
      try {
        const parsed = JSON.parse(jsonGraph);
        graph.fromJSON(parsed);
        setError(null);
        
        setTimeout(() => {
          if (paperRef.current) {
            paperRef.current.scaleContentToFit({ padding: 30 });
          }
        }, 50);

      } catch (err) {
        console.error("Failed to parse JointJS JSON", err);
        setError("Invalid JointJS JSON payload generated by the AI. Please try generating again.");
      }
    } else {
      graph.clear();
    }
  }, [jsonGraph]);

  return (
    <div className="w-full h-full relative" style={{ minHeight: '400px' }}>
      {error && (
        <div className="absolute inset-0 flex items-center justify-center bg-red-500/10 text-red-500 font-semibold p-4 text-center z-10">
          {error}
        </div>
      )}
      <div ref={canvasRef} className="w-full h-full overflow-hidden" />
    </div>
  );
}
